apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MYSQL_DATABASE: bmV4dGNsb3Vk 
  MYSQL_USER: bmV4dGNsb3Vk 
  MYSQL_PASSWORD: gPuGthH9XLBHkjIa 
  MYSQL_ROOT_PASSWORD: gPuGthH9XLBHkjIa
  
